# Generated by Django 5.1.7 on 2026-04-04 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("a15cd45b-d116-49ac-87a6-961adedaf58c"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("current_status", models.CharField(max_length=255)),
                ("next_status", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("c7e1fad0-9fc0-444f-8d67-8f9694c1c7f3"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("booking_number", models.CharField(max_length=255, null=True)),
                ("deposit_paid", models.BooleanField(default=False)),
                (
                    "amount_expected",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=100)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slotbookings",
                        to="spaces.spaceslot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
