# Generated by Django 5.1.7 on 2026-04-04 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5c27650c-f50b-4c4b-9cea-505d3399c383"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatus",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f95bc374-cca8-4658-a9e5-93bd004a7536"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
