# Generated by Django 5.1.7 on 2026-04-04 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="Member", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("282f5e56-eee7-48d1-95a8-3af8dbc3b747"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
