# Generated by Django 5.1.7 on 2026-04-04 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e97884b4-7cba-4466-9e08-a1b2bc7d13eb"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="spacecomponent",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("615320cb-9526-4091-9640-9aab0c570283"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="spaceslot",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("78ce6386-829c-45f5-8bc1-63be6bed0791"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
